### ISSUE TITLE
Creative Assignment 1 Submission 

### ISSUE THREAD

**Issue by maggieweese** [VIS-2129-F2020/maggieweese-vis#1]
Hi Carole and Aleksandar,

I hope you are both well! The .Rmd and html file for creative assignment 1 are finished and ready for grading. 

HTML
file:///C:/Users/admin/Documents/Grad%20School%20-%20Harvard/GSD/Vis/GitHub/maggieweese-vis/Excercise-1---Maggie-Weese_final.html

Looking forward to your comments and feedback.

All the best,
Maggie

**Comment by bauranov** [comment]
Good job! Here are some comments:
- The link for the assignment should be https://vis-2129-f2020.github.io/maggieweese-vis/filename instead of the path to local directory on the computer.
- In the link you provided above, the name of the assignment is Excercise-1---Maggie-Weese_final.html, however, in your Github repo there's no such file, only Excercise-1---Maggie-Weese.html. For whatever reason, I couldn't open that file. I knitted rmd file so I was able to review it, but always make sure to test the final submitted file by checking if https://vis-2129-f2020.github.io/maggieweese-vis/Excercise-1---Maggie-Weese.html works. 
- Use {r message=FALSE} to suppress messages in the knitted file. 

Other than that, everything else looks good. Keep up the good work!
